### Creates a new flight
POST http://localhost:3000/flights
Content-Type: application/json

{
  "number": "0003",
  "source": "Aeropuerto Internacional de las Americas",
  "destination": "Aeropuerto El Dorado",
  "departurDateTime": "2022-12-29 21:00",
  "arrivalDateTime": "2022-12-30 05:00",
  "airlineId": "57611992-7841-4c36-91d5-aa9b638cb2b0"
}