### Creates a new flight
POST http://localhost:3000/flights
Content-Type: application/json

{
  "number": "2021",
  "source": "Aeropuerto Internacional de las Americas",
  "destination": "Aeropuerto El Dorado",
  "departurDateTime": "2022-12-29 21:00",
  "arrivalDateTime": "2022-12-30 05:00",
  "airlineId": "8b5c8209-6442-4130-ba9b-bde16a6aaae2"
}